JavasScript expert
raycast/preset-explorer pull request #13
Opened 2024-06-21 09:38 UTC by vicainelli

2024-06-24 12:18 UTC, samuelkraft requested changes
Thanks @vicainelli! Can you please add your author name + link, then it's ready to merge.

2024-06-24 12:18 UTC, samuelkraft commented on data/presets.ts
> +  Here are some rules:
Remove whitespace

2024-06-24 12:18 UTC, samuelkraft commented on data/presets.ts
> +    },
Add author name + link

2024-06-24 12:28 UTC, vicainelli commented on data/presets.ts
> +    },
Oh, thanks the reminder.

2024-06-25 10:38 UTC, samuelkraft approved these changes

2024-06-25 10:38 UTC, merged